"""Initial migration

Revision ID: 6ce81da9e8cb
Revises: 
Create Date: 2024-05-09 02:17:23.758491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = '6ce81da9e8cb'
down_revision = None
branch_labels = None
depends_on = None

# modified to resolve table already exist errors
def upgrade():
    # Get the current connection
    conn = op.get_bind()

    # Use SQLAlchemy reflection to check if the 'station' table exists
    inspector = reflection.Inspector.from_engine(conn)
    existing_tables = inspector.get_table_names()

    if 'station' not in existing_tables:
        # ### commands auto generated by Alembic - please adjust! ###
            op.create_table('station',
            sa.Column('station_id', sa.Integer(), nullable=False),
            sa.Column('station_name', sa.String(length=120), nullable=False),
            sa.Column('station_postcode', sa.Integer(), nullable=True),
            sa.Column('station_phone_number', sa.String(length=20), nullable=True),
            sa.Column('station_address', sa.String(length=255), nullable=True),
            sa.PrimaryKeyConstraint('station_id')
            )
    # Create 'user' table if it does not exist
    if 'user' not in existing_tables:
        op.create_table('user',
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('user_name', sa.String(length=120), nullable=False),
            sa.Column('user_password', sa.String(length=20), nullable=False),
            sa.Column('user_email', sa.String(length=120), nullable=False),
            sa.PrimaryKeyConstraint('user_id'),
            sa.UniqueConstraint('user_email')
        )
    # Create 'post' table if it does not exist
    if 'post' not in existing_tables:
        op.create_table('post',
            sa.Column('post_id', sa.Integer(), nullable=False),
            sa.Column('superior_post_id', sa.String(length=120), nullable=False),
            sa.Column('post_title', sa.String(length=255), nullable=False),
            sa.Column('post_content', sa.Text(), nullable=False),
            sa.Column('post_author_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['post_author_id'], ['user.user_id'], ),
            sa.PrimaryKeyConstraint('post_id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    op.drop_table('station')
    # ### end Alembic commands ###
